 <!DOCTYPE html> 
<html lang="en"> 
	<head>
	<!-- handcrafted in html5 by Matthew Eric Bassett/gegn corp - http://mebassett.gegn.net -->
	

		<title>Control Panel | Sneffel</title>
		
		<meta name="description" content="Sneffel is a beta web app that changes online education through real time collaboration." />
		<meta name="keywords" content="real time collaboration,education , whiteboard, drawing, fun" />		
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				
		<link rel="shortcut icon" href="/favicon.gif" />		
		<link rel="stylesheet" type="text/css" href="/newstyle2.css" media="screen" />
		<link rel="stylesheet" type="text/css" href="/resources/dashboard.css" media="screen" />
		<link rel="stylesheet" type="text/css" href="/resources/home.css" media="screen" />
		
		<script type="text/javascript" src="/jquery.js" ></script>
		<script type="text/javascript" src="/resources/dashboard.js" ></script>

		<!--[if lt IE 9]>
				<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]--> 
		<!--[if lte IE 6]>
			<link type="text/css" rel="stylesheet" href="css/obsolete.css">
			<?php include "google.phtml"; ?></head>
			<body>
				<h6>This site looks best in a modern browser, such as the latest versions of Chrome, Safari, or Firefox</h6>
		<![endif]--> 

		
	<?php include "google.phtml"; ?></head>
	<body>
		<header>
<h1 class="logo">Sneffel (<span>the beta</span>)</h1>
			<h1>Changing online education.</h1>
			<?php include "nav-standard.inc.phtml"; ?>
		</header>
		
		<div class="main">
		<h1>Welcome back, <?=$user->name?>.</h1>
		<?php if($errStr){ ?>
			<h3><?=$errStr?></h3>
		<?php } ?>
	
		<section class="credits">
			<p>SneffelCredits: <strong><?=$user->credit?></strong> <a href="/purchase">Purchase More</a> <a href="/boardCreator">Make Custom Board</a> <a href="/new">Normal Board</a></p> 
		</section>
		
		
		
		

		<span id="possibleBoards">
			<?php include "operationGetPossibleBoards.phtml"; ?>
		</span>
		
		<span id="userBoards">		
			<?php include "operationGetUserBoards.phtml"; ?>
		</span>
	
		</div>

		
		<footer>

				
			
			<?php include "copy.inc.phtml"; ?>			
		</footer>

		<div id="customerService">
			Need help or support?  You can reach me (Matthew) at:<br/>
			Skype: mebassett<br/>
			Twitter: <a href="http://www.twitter.com/mebassett">@mebassett</a><br/>
			Email: <a href="mailto:mebassett@gegn.net">matthew@sneffel.com</a><br/>
			Phone: +1 (719) 266 2314
		</div>


	
	</body> 
	
</html>
