 <!DOCTYPE html> 
<html lang="en"> 
	<head>
	<!-- handcrafted in html5 by Matthew Eric Bassett/gegn corp - http://mebassett.gegn.net -->
	

		<title>Changing online education - Sneffel</title>
		
		<meta name="description" content="Sneffel is a beta web app that changes online education through real time collaboration." />
		<meta name="keywords" content="real time collaboration,education , whiteboard, drawing, fun" />


		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				
		<link rel="shortcut icon" href="/favicon.gif" />		


		<link rel="stylesheet" type="text/css" href="/resources/home.css" media="screen" />
		<script type="text/javascript" src="/jquery.js" ></script>
		<script type="text/javascript" src="/resources/jquery-ui.js" ></script>
		<script type="text/javascript" src="/resources/home.js" ></script>

		<!--[if lt IE 9]>
				<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
		<![endif]--> 
		<!--[if lte IE 6]>
			<link type="text/css" rel="stylesheet" href="css/obsolete.css">
			</head>
			<body>
				<h6>This site looks best in a modern browser, such as the latest versions of Chrome, Safari, or Firefox</h6>
		<![endif]--> 

	      <style>
    div.links {height:50px;padding-top:15px;}
    div.links a, div.links a:visited
			{
				font-family: "headerNav",verdana, sans-serif;
				color: #19A0CC;
				margin-left:10px;
				padding:8px;
				
				background-color:#C9EDF9;
					-moz-border-radius: 5px;
				-webkit-border-radius: 5px;

			}
			div.links a:hover
			{
				color: #0F5F79;
				background-color:#19A0CC;
			} 	

    </style>
	<?php include "google.phtml"; ?></head>
	<?php
	$s = $app->db->prepare("select count(id) as num from DoodleBoard where 1");$s->execute();$num=$s->fetchObject();
?>
	<body>
		<header>
			<h1 class="logo">Sneffel (<span>beta</span>)</h1>
			<h1><?=$num->num?> SneffelBoards served.</h1>
		</header>
		
		
		<div class="main">
		
		
<h1>Sneffel lets online students interact with each other with their own virtual whiteboard.</h1>

<div class="box" style="font-size:1.5em">

It's a virtual drawing pad that lets student and teachers collaborate.<br/><br/>
It's a collaborative equation editor that lets students engage each other.<br/><br/>
It records your work and lets you replay it again and again.

</div>

<div class="links">
	<a href="/new">new board</a> 
	<a href="/signup">new sneffel school</a> 	
</div>
												   <p style="text-align:center">Try the sample SneffelSchool at <a href="http://community.sneffel.com">http://community.sneffel.com</a>.</p>

<p  style="font-size:1.4em;margin-bottom:10px;">See how to use Sneffel to:</p>
		
			<div id="vid1" style="text-align:center;">					
					<object width="700" height="560">
					<param name="movie" value="http://www.youtube.com/v/SJwSknvHe8k&amp;hl=en_US&amp;fs=1" />
					<param name="allowFullScreen" value="true"/>
					<param name="allowscriptaccess" value="always"/>
					<embed src="http://www.youtube.com/v/SJwSknvHe8k&amp;hl=en_US&amp;fs=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="700" height="560"/>
				</object>			
			</div>
			<div id="vid2" style="text-align:center;">
				<object width="700" height="560">
					<param name="movie" value="http://www.youtube.com/v/EDLIKMgPj5I&amp;hl=en_US&amp;fs=1" />
					<param name="allowFullScreen" value="true"/>
					<param name="allowscriptaccess" value="always"/>
					<embed src="http://www.youtube.com/v/EDLIKMgPj5I&amp;hl=en_US&amp;fs=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="700" height="560"/>
				</object>
			</div>
			<div id="vid3" style="text-align:center;">
				<object width="700" height="560">
					<param name="movie" value="http://www.youtube.com/v/LixaMv1xMrk&amp;hl=en_US&amp;fs=1" />
					<param name="allowFullScreen" value="true"/>
					<param name="allowscriptaccess" value="always" />
					<embed src="http://www.youtube.com/v/LixaMv1xMrk&amp;hl=en_US&amp;fs=1" type="application/x-shockwave-flash" allowscriptaccess="always" allowfullscreen="true" width="700" height="560"/>
				</object>
			</div>

<div style="text-align:center; font-size:1.2em">
<a href="#vid1" class="modal">create a custom drawing pad.</a> - <a href="#vid2" class="modal">collaborate with a friend.</a> - <a href="#vid3" class="modal">build a mathematics presentation.</a>
</div>


<div class="box">
Sneffel is currently in beta and you can create a new SneffelBoard for free. If you're interested in using Sneffel in your school, please contact Matthew: matthew [at] sneffel [dot] com.  Additionally, if you'd like to support Sneffel, please feel free to <strong>donate</strong>.
<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
<input type="hidden" name="cmd" value="_s-xclick">
<input type="hidden" name="hosted_button_id" value="6JL53QPMW4L9C">
<input type="image" src="https://www.paypal.com/en_US/i/btn/btn_donateCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
<img alt="" border="0" src="https://www.paypal.com/en_US/i/scr/pixel.gif" width="1" height="1">
</form>


</div>





		</div>

		
		<footer>

				
			
			<?php include "copy.inc.phtml"; ?>			
		</footer>

		<div id="boxes">		

			
			<div id="mask"></div>  
		</div>

										       
<!-- Google Website Optimizer Tracking Script -->
<script type="text/javascript">
if(typeof(_gat)!='object')document.write('<sc'+'ript src="http'+
(document.location.protocol=='https:'?'s://ssl':'://www')+
'.google-analytics.com/ga.js"></sc'+'ript>')</script>
<script type="text/javascript">
try {
var gwoTracker=_gat._getTracker("UA-252376-7");
gwoTracker._trackPageview("/2342355866/test");
}catch(err){}</script>
<!-- End of Google Website Optimizer Tracking Script -->

	
	</body> 
	
</html>
