<!DOCTYPE html> 
<html lang="en"> 
	<head>
	<!-- handcrafted in html5 by Matthew Eric Bassett/gegn corp - http://mebassett.gegn.net -->
		<title>?=$board->name?> - Sneffel Embedded Board</title>
		<link rel="shortcut icon" href="/favicon.gif" />		
		<link rel="stylesheet" type="text/css" href="/resources/whiteboardEmbed.css" media="screen" />
		<link rel="stylesheet" type="text/css" href="/css/jquery-ui.css" media="screen" />
		<link rel="stylesheet" media="screen" type="text/css" href="/resources/css/colorpicker.css" />
		<script type="text/javascript" src="/jquery.js" ></script>
		<script type="text/javascript" src="/resources/jquery-ui.js" ></script>
		<script type="text/javascript" src="/jscolor/jscolor.js"></script>
		<script type="text/javascript" src="/resources/swfobject.js"></script>
		<script type="text/javascript" src="/resources/FABridge.js"></script>
		<script type="text/javascript" src="/resources/web_socket.js"></script>		
		<script type="text/javascript" src="/resources/DoodleBoard.js" ></script>
		<script type="text/javascript" src="/resources/whiteboardEmbed.js" ></script>	
		<script>
			var roomId=<?=$roomId?>;
			var sneffelWidth=<?=$width?>;
			var sneffelHeight=<?=$height?>;
		</script>
		<style type="text/css">

			
			body{
	margin:0; padding:0;
	font-family: "myfont2",verdana, sans-serif;
	background-color:#<?=$board->backgroundColor?>;text-align:center;
	height:100%;}
			header{
	padding:0;<?php if($heightAdjust) { ?> height:<?=$heightAdjust?>; <?php } ?>;text-align:center;
}
div#controls {
background-color: #<?=$board->backgroundColor?>; /* for non-css3 browsers */
width:<?=$width?>px;height:<?=$height?>;
}
		</style>		
	<?php include "google.phtml"; ?></head>
	<body>
		<header>
			<img src="<?=$board->brandImage?>" alt="<?=$board->name?>"/>
		</header>
				<!--[if lt IE 9]>
				<strong>Sneffel requires a browser that supports the Canvas tag and WebSockets, such as Firefox, Chrome, or Safari.</strong>
				<![endif]--> 			
		<div id="controls">
	
			<section>
				<button id="drawButton" class="buttonClick"></button>
				<button id="eraseButton"></button>
				
				<div id="slider"></div>
				<div id="showSize">1</div>
				<input id="penColor" name="penColor" class="color" value="<?=$color?>"  />
				<button id="uploadButton"></button>
			</section>

			<div id="drawPadBox">				
				<canvas id="drawPad" width="2000" height="2000">
					no canvas support
				</canvas>
			</div>
			<div class="bottomControls">
				
				<form target="formHelper" method="post" action="/opPostText">
					<label id="usersOnline">1 Person drawing.</label> 
					<input type="hidden" id="formSize" name="formSize" value="1" /> 
					<input type="hidden" id="formColor" name="formColor" value="<?=$color?>" />					
					<input class="textPost" name="text" type="text" value="insert text here (\LaTeX works!)" />
					<input name="submit" id="submitButton" type="submit" value="Post" />
				</form>
			</div>
		</div>
		<iframe id="formHelper" onload="onHelperLoad();" name="formHelper" style="margin-left:-10000px;display:none;visibility:hidden;height:1px;" on></iframe>
 
		<iframe id="loader" onload="onLoader();" name="loader" style="margin-left:-10000px;display:none;visibility:hidden;height:1px;" on></iframe>
		
		<div id="boxes">		
			<div id="uploadBox" class="window">		
				<form id="uploadPic" enctype="multipart/form-data" target="formHelper" action="/opUploadBoardPic" method="post">				
					<label for="boardPic">Upload Picture</label>
					<input id="boardPic" name="boardPic" type="file"  />
					<input type="submit" name="upload" value="Upload" class="button"/>						
				</form>		
				<p><a href="#" class="close">Cancel</a></p>
			</div>
			<div id="loading" class="window">
				Sneffel is loading your whiteboard.
			</div>
			<div id="error" class="window">
				<h1>Oops.</h1>
				<p id="errMsg">Something has went terribly wrong.  Please try again. Sorry.</p>

			</div>
			
			<div id="mask"></div>  
		</div>

	
	</body> 
	
</html>
		