<!DOCTYPE html> 
<html lang="en"> 
	<head>
	<!-- handcrafted in html5 by Matthew Eric Bassett/gegn corp - http://mebassett.gegn.net -->
	

		<title>Collaborative Doodle Pad - Sneffel</title>
		<meta name="description" content="Sneffel is a beta web app that changes online education through real time collaboration." />
		<meta name="keywords" content="real time collaboration,education , whiteboard, drawing, fun" />
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
				
		<link rel="shortcut icon" href="/favicon.gif" />		
		<link rel="stylesheet" type="text/css" href="/resources/replayLight.css" media="screen" />
		<link rel="stylesheet" type="text/css" href="/css/jquery-ui.css" media="screen" />
		<link rel="stylesheet" media="screen" type="text/css" href="/resources/css/colorpicker.css" />
		<!--[if lt IE 9]>
				<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
				<script src="/resources/excanvas.js"></script>
		<![endif]--> 
		
		

		<script type="text/javascript" src="/jquery.js" ></script>
		<script type="text/javascript" src="/resources/jquery-ui.js" ></script>
		<script type="text/javascript" src="/resources/jquery.preload.js" ></script>

		
		<script type="text/javascript" src="/resources/swfobject.js"></script>
		<script type="text/javascript" src="/resources/FABridge.js"></script>
		<script type="text/javascript" src="/resources/web_socket.js"></script>		
		<script type="text/javascript" src="/resources/DoodleBoard.js" ></script>
		<script type="text/javascript" src="/resources/Replay.js" ></script>
		<script>
			var roomId=<?=$roomId?>;
			var picturesLoaded=false;
			heightAdjust = <?=$heightAdjust?>;
			function startPreload()
			{
				var urls=<?=$imgText?>;
				$.preload(urls,{onFinish:function(){
					picturesLoaded=true;
					if(socket.readyState ==1)
						socket.send('{"type":"SYSreplayBoard","roomId":'+roomId+'}');
					$('#mask, .window').hide();
				}});
			}
		</script>
		
		<style type="text/css">		
			body{
	margin:0; padding:0;
	font-family: "myfont2",verdana, sans-serif;
	background-color:#<?=$board->backgroundColor?>;text-align:center;
	height:100%;}
			header{
	padding:0;text-align:center;
}
header > p {margin-top:0px; margin-bottom:0px;}
div#controls {
background-color: #<?=$board->backgroundColor?>; /* for non-css3 browsers */

}
header > p > a, header > p > a:visited
{
	font-weight:normal;
	text-decoration:none;
}
header > p > a:hover
{
	text-decoration:underline;
}p.error{color:red;margin-top:0px;margin-bottom:5px;}
		</style>		
	<?php include "google.phtml"; ?></head>
		<header>
			<?php if($board->brandImage) {?>
				<img src="<?=$board->brandImage?>" alt="Sneffel (Virtual Paper)"/>
			<?php } ?>
			<p>Replaying <?= ($board->name) ? urldecode($board->name) : "[board #".$board->id."]" ?></p>
		</header>
				<!--[if lt IE 9]>
				<strong>Sneffel requires a browser that supports the Canvas tag and WebSockets, such as Firefox, Chrome, or Safari.</strong>
				<![endif]--> 			
		<div id="controls">
	
			<div id="drawPadBox">				
				<canvas id="drawPad" width="2000" height="2000">
					no canvas support
				</canvas>
			</div>
			<div class="bottomControls">
				<button id="restart">Start over!</button>
				<span id="marker">0&#37; Complete.</span>
			</div>
		</div>
		
					<footer>
			<nav>			
				<ul>			
						<li>  
							<a href="/<?=$roomId?>">back to board</a>
						</li>			
						<li>  
							<a href="/">home</a>
						</li>


					
				</ul>		
			</nav>				
				
			<div id="invite">
				You can share this animation: <input style="width:280px" readonly="readonly" value="http://<?=$school->domain?>.sneffel.com/replay/<?=$roomId?>" /><br/>&nbsp;
				
			</div>
	
			<div id="embed">
				Embed code:<br/>
				<textarea type="text" readonly="readonly" rows="2" cols="35"><?=htmlspecialchars($embedText)?></textarea> 
			</div>	
			
				<?php include "copy.inc.phtml"; ?>					
		</footer>
				<div id="views">
   				This board has been replayed <strong><?=$obj->views?></strong> time<?=($obj->views==1) ? "" : "s"?>.
			</div>		
		
		<div id="boxes">		

			<div id="error" class="window">
				<h1>Oops.</h1>
				<p id="errMsg">Something has went terribly wrong.  Please try again. Sorry.</p>

			</div>
						<div id="loading" class="window">
				Sneffel is loading your whiteboard.
			</div>
			
			<div id="mask"></div>  
		</div>





	</body> 
	
</html>
